### ISSUE TITLE
`addDts` breaks after removing the `src/env.d.ts` file inside a project

### ISSUE THREAD

**Issue by BryceRussell** [florian-lefebvre/astro-integration-kit#111]
`addDts` breaks after deleting the `src/env.d.ts` file inside a project. Series of events:

1. User deletes `src/env.d.ts` file inside a project
2. User gets an error that the `src/env.d.ts` file doesn't exist
3. User creates an empty `src/env.d.ts` file to fix error
4. `addDts` silently fails to add an entry to the new file because it is empty and does not contain the reference `/// <reference types='astro/client>`

`addDts` breaks in two of these steps:
- ***Step 2***: `addDts` runs before Astro can [create and seed](https://github.com/withastro/astro/blob/1296cb9b1a50aa9b6e21db9551829922a63cf953/packages/astro/src/vite-plugin-inject-env-ts/index.ts#L101) the `src/env.d.ts` file. This causes an [error when trying to read the file](https://github.com/florian-lefebvre/astro-integration-kit/blob/main/package/src/utilities/add-dts.ts#L26) because the file doesn't exist.
- ***Step 4***: If the `src/env.d.ts` file is empty, `addDts` does not add type references to the file because the `/// <reference types='astro/client>` reference does not exist.

Possible solutions:
- AIK could create a `src/env.d.ts` file if it doesn't exist and seed empty `src/env.d.ts` files with the client reference ([like Astro does](https://github.com/withastro/astro/blob/1296cb9b1a50aa9b6e21db9551829922a63cf953/packages/astro/src/vite-plugin-inject-env-ts/index.ts#L103))
- Defer execution of `addDts` until after Astro generates a `src/env.d.ts` file

**Why are you even deleting `src/env.d.ts`? What is your use case?**

Sometimes I delete the file so that it can regenerate because there might be unused references from `addDts` or older versions of Astro

**Comment by florian-lefebvre** [comment]
Interesting! I guess delaying would be better but I think that requires moving `addDts` to another hook?

**Comment by BryceRussell** [comment]
Maybe it could be delayed using a hook inside a Vite plugin so that it can stay inside of the `astro:config:setup` hook

**Comment by florian-lefebvre** [comment]
Yeah I think that would work https://github.com/withastro/astro/blob/main/packages%2Fastro%2Fsrc%2Fvite-plugin-inject-env-ts%2Findex.ts#L30

**Comment by florian-lefebvre** [comment]
I'm not planning on fixing this anymore since there's now a utility in core https://docs.astro.build/en/reference/integrations-reference/#injecttypes-options
