### ISSUE TITLE
Astro 5 support

### ISSUE THREAD

**Issue by anotheri** [florian-lefebvre/astro-integration-kit#120]
When i install the package to astro 5 project I get this warning:

> astro is listed by your project with version 5.0.0-beta.6 (peec57), which doesn't satisfy what astro-integration-kit (via @yeskunall/astro-umami) and other dependencies request (^4.16.7 || ^4.16.7).

Could you please update `peerDependencies`?

**Comment by florian-lefebvre** [comment]
Do you want to submit a PR for it? It should be `^4.12.0 || ^5.0.0-beta` I believe

**Comment by florian-lefebvre** [comment]
Should work from 0.17.0
