### ISSUE TITLE
Has integration check integration position

### ISSUE THREAD

**Issue by Fryuni** [florian-lefebvre/astro-integration-kit#33]
Just like this kit provides `hasIntegration` to check if an integration was already included, it could provide a `hasPreviousIntegration`/`hasFollowingIntegration` for integrations that interact with others in specific orders (mostly related to markdown and MDX).

This would allow the integration to issue a warning or an error if an integration was added in the incorrect order.

**Comment by florian-lefebvre** [comment]
Sounds good!

**Comment by Fryuni** [comment]
Gonna work on this!
