### ISSUE TITLE
TS quirk for third-party plugins

### ISSUE THREAD

**Issue by Fryuni** [florian-lefebvre/astro-integration-kit#50]
If you do this:
```ts
export const somePlugin = definePlugin();
```

The inferred type of `somePlugin` requires importing transitive dependencies to be named (even if it is also your dependency) because it relies on AIK's dependency in Astro.
Because a third-party lib may depend on a different version of Astro, `import('astro')` would refer to different types depending on where it is. So TS rejects that just for the possibility, even if it is not really the case.

This problem happens for libs that are transpiled and emit a .d.ts. The two solutions are:
- Set emitDeclarations and declarationsMap to false and publish the source TS files (like AIK does)
- Explicitly create a named type for the plugin, like so:
  ```ts
  type SomePlugin = Plugin<
  	'utilityName',
  	'astro:config:setup',
  	(p: HookParams) => (params: UtilityParams) => UtilityOutput
  >;

  export const somePlugin: SomePlugin = definePlugin();
  ```

**Comment by florian-lefebvre** [comment]
I better understand thanks! Well, I guess your first point is better DX wise but as long as there's a workaround, that's fine!

**Comment by Fryuni** [comment]
Btw, I think the third parameter of the `Plugin` type could be just signature of the hook, without the hook parameters input since those can be retrieved by the hook name on the second parameter.

Would be a breaking change, but might something to be improve when adding inter-plugins dependency.
