### ISSUE TITLE
[feature] Warn (or fail) when adding a Vite plugin that is already present

### ISSUE THREAD

**Issue by Fryuni** [florian-lefebvre/astro-integration-kit#51]
```ts
addVitePlugin(somePlugin()) // Fine

addVitePlugin(somePlugin()) // Warn, plugin already installed
```

Should work even if those are two different integrations

**Comment by florian-lefebvre** [comment]
Do you think having a utility `hasVitePlugin` (basically https://github.com/Fryuni/inox-tools/blob/main/packages/aik-mod/src/index.ts) would be enough?

**Comment by Fryuni** [comment]
It would be helpful but relies on the integration author checking before adding the plugin they use.

The warning would be more for cases where two integrations add the same plugin, possibly with different configurations. It will not behave as the integration expects.

For example, imagine Expressive Code. It adds its Vite Plugin to pass options to runtime. If it was already added previously, that earlier plugin will resolve the virtual module, not the newly added plugin. This would be hard to debug since both plugins are the same file, just configured differently.

In that scenario, we could log something like:
```
WARN [<integration using AIK>] The Vite plugin "<plugin name>" is already present in your Vite configuration. The plugin might not behave correctly.
```

An author could use the `hasVitePlugin` to provide a better message and/or have some flag to not try to add the plugin

**Comment by florian-lefebvre** [comment]
Alright so proposal:
1. new utility `hasVitePlugin`
2. Add a new argument to `addVitePlugin`: `warnDuplicated` (set to true by default)

**Comment by BryceRussell** [comment]
I was exploring this but I hit a bit of a roadblock because the `config` in the `astro:config:setup` hook does not get updated with any values added from inside the integration. This means you can only check for Vite plugins that were added from previously loaded integrations and not the current integration. How do you check for a Vite plugin inside the current integration if you can't use `config.vite.plugins`?

**Comment by Fryuni** [comment]
> This means you can only check for Vite plugins that were added from previously loaded integrations and not the current integration.

The current integration is using AIK, so we can interfere at will :)

We have some options:


## Option A: Detect only for repeated `addVitePlugin` hook param

```ts
definePlugin({
  name: 'addVitePlugin',
  hook: 'astro:config:setup',
  implementation: ({updateConfig}) => {
    const addedPlugins = new Set<string>();
    return (plugin) => {
      // the implementation
      addedPlugins.add(plugin.name);
    };
  },
});
```

## Option B: Patching the `updateConfig` hook param

This can be on the `hasVitePlugin`

```ts
definePlugin({
  name: 'hasVitePlugin',
  hook: 'astro:config:setup',
  implementation: (astroConfig) => {
    // Prepopulate with previous plugins
    const addedPlugins = new Set<string>(astroConfig.vite.plugins.map(
      // Has to handle arrays recursively, but you get the idea
      plugin => plugin.name,
    ));

    const {updateConfig: original} = astroConfig;

    astroConfig.updateConfig = (config) => {
      for (const plugin of config?.vite?.plugins ?? []) {
        // Has to handle arrays recursively, but you get the idea
        if (plugin) addedPlugins.add(plugin.name);
      }
      return original(config);
    };

    return (name: string) => {
      return addedPlugins.has(name);
    };
  },
});
```

## Option C: Keep an external map so it works even when using utilities

This one is kinda tricky because it can track only what is added from the `addVitePlugin` and not directly to `updateConfig`, but it works with the utility as well instead of just the hook param.

```ts
const sharedMap = new WeakMap<AstroConfig, Set<string>>();

export function addVitePlugin({plugin, updateConfig}) {
  // Do the adding
  
  const plugins = sharedMap.get(updateConfig);
  if (plugins) {
    plugins.add(plugin.name);
  } else {
    sharedMap.set(updateConfig, new Set([plugin.name]);
  }
}

export function hasVitePlugin({name, config, updateConfig}: {
  name: string;
  config: AstroConfig;
  updateConfig?: TheFunctionTypeThatIDontRememberTheName;
}) {
  // check the astro config
  
  if (updateConfig) {
    return sharedMap.get(updateConfig)?.has(name) ?? false;
  }

  return false;
}
```

---

I personally prefer the path of option B, and document that this doesn't handle plugins added previously in the same integration when using the utility version

**Comment by BryceRussell** [comment]
Wow, thanks for such a detailed response! I agree option B seems it would be the best, it is a good balance between being simple and having reasonable limitations. I will explore option B and see how it works, thanks again!

**Comment by BryceRussell** [comment]
I was able to get option B working nicely, but I have one more question before I am ready to open a draft PR: Now that `addVitePlugin` checks for existing plugins and logs a warning, it needs the arguments `warnDuplicated`, `config`, and `logger`. 

```diff
// addVitePlugin util args
{
	plugin: PluginOption;
+       warnDuplicated?: boolean;
+       config: HookParameters<"astro:config:setup">["config"];
+       logger: HookParameters<"astro:config:setup">["logger"];
	updateConfig: HookParameters<"astro:config:setup">["updateConfig"];
}
```

This means all the other utils that use `addVitePlugin` like `addVirtualImports` would also need the `config`, `logger` and possibly `warnDuplicated` arguments.

```diff
// addVirtualImports util args
{
	name: string;
	imports: Record<string, string>;
+       warnDuplicated?: boolean;
+       config: HookParameters<"astro:config:setup">["config"];
+       logger: HookParameters<"astro:config:setup">["logger"];
	updateConfig: HookParameters<"astro:config:setup">["updateConfig"];
}
```

This seems like a rather large breaking change and I was hoping to keep it minimal. Is this right? Should I add these arguments to the utils that use `addVitePlugin`?

**Comment by Fryuni** [comment]
I think those options should only be necessary when `warnDuplicate` is not `false`.

`addVirtualImports` and `addDevToolbarFrameworkApp` can probably set that to `warnDuplicated: false` since we generate the plugin name inside of AIK anyway.
