### ISSUE TITLE
After adding from npm, the type is not identified.

### ISSUE THREAD

**Issue by ktym4a** [florian-lefebvre/astro-integration-kit#54]
When using devtool in a workspace, typescript type inference works correctly, but type inference does not work after adding from npm

this one is in a workspace.
![workspace](https://github.com/florian-lefebvre/astro-integration-kit/assets/51779800/d65445bd-3869-4c2d-905f-0e880da374d1)

---

this one is added from npm
![npm](https://github.com/florian-lefebvre/astro-integration-kit/assets/51779800/efefd196-e494-477c-ba5d-dde8a39c8d64)

**Comment by florian-lefebvre** [comment]
Is the repo public? Without the code, a bit hard to say!

**Comment by ktym4a** [comment]
yes it is.
https://github.com/ktym4a/astro-page-insight

**Comment by florian-lefebvre** [comment]
I'll have a look at it later today

**Comment by florian-lefebvre** [comment]
Looking at this repro (https://stackblitz.com/edit/withastro-astro-cag46f?file=astro.config.mjs), it seems that this does not occur with all package managers:
- pnpm: works
- npm: broken
- yarn: unknown

**Comment by ktym4a** [comment]
I tested and seems that

- pnpm: works
- npm: broken
- yarn: broken

**Comment by florian-lefebvre** [comment]
@Princesseuh do you know why that happens? I guess I must be missing some fields in `package.json`? https://github.com/florian-lefebvre/astro-integration-template/blob/main/package/package.json
