### ISSUE TITLE
Adding Astro Qwik to the showcase.

### ISSUE THREAD

**Issue by thejackshelton** [florian-lefebvre/astro-integration-kit#55]
Thought I might as well add it since I'm happily using it in the Qwik integration.

Feel free to copy paste this to save time haha or whatever you prefer.
```
[Astro Qwik](https://github.com/QwikDev/astro) - by Jack Shelton
```

**Comment by florian-lefebvre** [comment]
Feel free to submit a PR! There's the "Edit page" link at the bottom of https://astro-integration-kit.netlify.app/getting-started/showcase/

![image](https://github.com/florian-lefebvre/astro-integration-kit/assets/69633530/bfc57d1e-279b-45c3-b56f-40bf600041a5)

**Comment by thejackshelton** [comment]
> Feel free to submit a PR! There's the "Edit page" link at the bottom of https://astro-integration-kit.netlify.app/getting-started/showcase/
> 
> ![image](https://private-user-images.githubusercontent.com/69633530/304495417-bfc57d1e-279b-45c3-b56f-40bf600041a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDczMTEsIm5iZiI6MTcwNzg0NzAxMSwicGF0aCI6Ii82OTYzMzUzMC8zMDQ0OTU0MTctYmZjNTdkMWUtMjc5Yi00NWMzLWI1NmYtNDBiZjYwMDA0MWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE3NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YzhjYjM0N2JiNWY0YWQ5NzFkMTA4MTJkY2Q0MTc0MWRlNDYwZjdhNWE5YjBhYmM2YTExOGZkMGM0MzY5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xkKOuMKz-dO1ZyiUKJiIF7JuF46pKTAqcP9k39cAnps)

Ah gotcha, that was the plan until I saw the blockquote at the bottom telling me to make an issue. Will do that 👍

**Comment by thejackshelton** [comment]
PR Made

**Comment by florian-lefebvre** [comment]
> Ah gotcha, that was the plan until I saw the blockquote at the bottom telling me to make an issue. Will do that 👍

I'll update it
