### ISSUE TITLE
The `addVitePlugin` example code in the docs does not work.

### ISSUE THREAD

**Issue by ktym4a** [florian-lefebvre/astro-integration-kit#83]
`VitePWA` is of type `Plugin[]`, but `addVitePlugin` takes only `Plugin` type.

[Docs](https://astro-integration-kit.netlify.app/utilities/add-vite-plugin/)

[vite-plugin-pwa](https://github.com/vite-pwa/vite-plugin-pwa/blob/e195fe2379c378ad05d73e9fb5f9e5438c5c3a7d/src/index.ts#L11-L21)

![Screenshot 2024-03-18 at 16 50 36](https://github.com/florian-lefebvre/astro-integration-kit/assets/51779800/1e1ce87f-5407-48ae-b80e-e900f44e60f4)

I know we should probably change the docs example now, but do you plan to receive `Plugin[]` in the future?

PS. It's an example, so I'm not sure if it should be changed.

**Comment by BryceRussell** [comment]
Good catch! I think the correct type for this is [`PluginOption`](https://github.com/vitejs/vite/blob/72104f6de5398a1a0511404e8485b3b7721be537/packages/vite/src/node/config.ts#L122)

**Comment by florian-lefebvre** [comment]
You're right! Sounds like a quick fix if you want to tackle it @ktym4a!

**Comment by ktym4a** [comment]
Let me tackle it!
