### ISSUE TITLE
`addIntegration` shows type error.

### ISSUE THREAD

**Issue by ktym4a** [florian-lefebvre/astro-integration-kit#85]
This may be due to version/devDep mismatch.

<img width="1093" alt="313883775-ade834a4-688f-437f-bbac-8148b5c3b0f0" src="https://github.com/florian-lefebvre/astro-integration-kit/assets/51779800/bc69959a-1377-44e6-a9b4-c1ac33fdb436">

**Comment by florian-lefebvre** [comment]
Can you provide a minimal reproduction? I'll check if 0.7.0 fixes it

**Comment by ktym4a** [comment]
Reproduce it in `playground/integration/index.ts` on the `main` branch.

and I checked the `feat/build-step` branch and it seems to be fixed.
